// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace sft.Migrations
{
  [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class basesite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basesite));
        
        string IMigrationMetadata.Id
        {
            get { return "201501211229182_base site"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
