// <auto-generated />
namespace sft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class rentalupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rentalupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201501270903245_rental update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
