// <auto-generated />
namespace sft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class rentalmodtime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rentalmodtime));
        
        string IMigrationMetadata.Id
        {
            get { return "201501231047261_rental mod time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
